In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot

In [2]:
df=pd.read_csv('data.csv')

In [3]:
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2.0,h,NaN,SS,Jellis,03-09-2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2.0,h,1480000.0,S,Biggin,03-12-2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2.0,h,1035000.0,S,Biggin,04-02-2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3.0,u,NaN,VB,Rounds,04-02-2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3.0,h,1465000.0,SP,Biggin,04-03-2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
5,Abbotsford,40 Federation La,3.0,h,850000.0,PI,Biggin,04-03-2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
6,Abbotsford,55a Park St,4.0,h,1600000.0,VB,Nelson,04-06-2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
7,Abbotsford,16 Maugie St,4.0,h,NaN,SN,Nelson,06-08-2016,2.5,3067.0,...,2.0,2.0,400.0,220.0,2006.0,Yarra,-37.79650,144.99650,Northern Metropolitan,4019.0
8,Abbotsford,53 Turner St,2.0,h,NaN,S,Biggin,06-08-2016,2.5,3067.0,...,1.0,2.0,201.0,NaN,1900.0,Yarra,-37.79950,144.99740,Northern Metropolitan,4019.0
9,Abbotsford,99 Turner St,2.0,h,NaN,S,Collins,06-08-2016,2.5,3067.0,...,2.0,1.0,202.0,NaN,1900.0,Yarra,-37.79960,144.99890,Northern Metropolitan,4019.0
10,Abbotsford,129 Charles St,2.0,h,941000.0,S,Jellis,07-05-2016,2.5,3067.0,...,1.0,0.0,181.0,NaN,NaN,Yarra,-37.80410,144.99530,Northern Metropolitan,4019.0
11,Abbotsford,124 Yarra St,3.0,h,1876000.0,S,Nelson,07-05-2016,2.5,3067.0,...,2.0,0.0,245.0,210.0,1910.0,Yarra,-37.80240,144.99930,Northern Metropolitan,4019.0
12,Abbotsford,121/56 Nicholson St,2.0,u,NaN,PI,Biggin,07-11-2016,2.5,3067.0,...,2.0,1.0,4292.0,82.0,2009.0,Yarra,-37.80780,144.99650,Northern Metropolitan,4019.0
13,Abbotsford,17 Raphael St,4.0,h,NaN,W,Biggin,07-11-2016,2.5,3067.0,...,2.0,0.0,230.0,147.0,1860.0,Yarra,-37.80660,144.99360,Northern Metropolitan,4019.0
14,Abbotsford,98 Charles St,2.0,h,1636000.0,S,Nelson,08-10-2016,2.5,3067.0,...,1.0,2.0,256.0,107.0,1890.0,Yarra,-37.80600,144.99540,Northern Metropolitan,4019.0
15,Abbotsford,217 Langridge St,3.0,h,1000000.0,S,Jellis,08-10-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
16,Abbotsford,18a Mollison St,2.0,t,745000.0,S,Jellis,08-10-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
17,Abbotsford,6/241 Nicholson St,1.0,u,300000.0,S,Biggin,08-10-2016,2.5,3067.0,...,1.0,1.0,0.0,NaN,NaN,Yarra,-37.80080,144.99730,Northern Metropolitan,4019.0
18,Abbotsford,10 Valiant St,2.0,h,1097000.0,S,Biggin,08-10-2016,2.5,3067.0,...,1.0,2.0,220.0,75.0,1900.0,Yarra,-37.80100,144.99890,Northern Metropolitan,4019.0
19,Abbotsford,403/609 Victoria St,2.0,u,542000.0,S,Dingle,08-10-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
20,Abbotsford,2 Rich St,2.0,h,NaN,SP,Biggin,10-12-2016,2.5,3067.0,...,1.0,1.0,176.0,80.0,1925.0,Yarra,-37.79980,144.99720,Northern Metropolitan,4019.0
21,Abbotsford,25/84 Trenerry Cr,2.0,u,760000.0,SP,Biggin,10-12-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
22,Abbotsford,106/119 Turner St,1.0,u,481000.0,SP,Purplebricks,10-12-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
23,Abbotsford,411/8 Grosvenor St,2.0,u,700000.0,VB,Jellis,12-11-2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra,-37.81100,145.00670,Northern Metropolitan,4019.0
24,Abbotsford,40 Nicholson St,3.0,h,1350000.0,VB,Nelson,12-11-2016,2.5,3067.0,...,2.0,2.0,214.0,190.0,2005.0,Yarra,-37.80850,144.99640,Northern Metropolitan,4019.0
25,Abbotsford,123/56 Nicholson St,2.0,u,750000.0,S,Biggin,12-11-2016,2.5,3067.0,...,2.0,1.0,0.0,94.0,2009.0,Yarra,-37.80780,144.99650,Northern Metropolitan,4019.0
26,Abbotsford,22 Park St,4.0,h,1985000.0,S,Biggin,12-11-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,-37.80840,144.99420,Northern Metropolitan,4019.0
27,Abbotsford,13/84 Trenerry Cr,1.0,u,500000.0,S,Biggin,12-11-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
28,Abbotsford,45 William St,2.0,h,1172500.0,S,Biggin,13-08-2016,2.5,3067.0,...,1.0,1.0,195.0,NaN,NaN,Yarra,-37.80840,144.99730,Northern Metropolitan,4019.0
29,Abbotsford,7/20 Abbotsford St,1.0,u,441000.0,SP,Greg,14-05-2016,2.5,3067.0,...,1.0,1.0,0.0,NaN,NaN,Yarra,-37.80160,144.99880,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23648,Vermont South,2 Settlers Ct,4.0,h,1295000.0,SP,Purplebricks,26-08-2017,17.2,3133.0,...,2.0,2.0,NaN,190.0,1980.0,NaN,-37.85928,145.18715,Eastern Metropolitan,4280.0
23649,Vermont South,9 Winswood Cl,4.0,h,1250000.0,PI,Philip,26-08-2017,17.2,3133.0,...,2.0,2.0,986.0,NaN,NaN,NaN,-37.84679,145.20051,Eastern Metropolitan,4280.0
23650,Viewbank,149 Graham Rd,5.0,h,1316000.0,SP,Nelson,26-08-2017,8.9,3084.0,...,3.0,3.0,696.0,NaN,NaN,NaN,-37.73501,145.08341,Eastern Metropolitan,2698.0
23651,Viewbank,7 Northwood Dr,4.0,h,NaN,SP,Nelson,26-08-2017,8.9,3084.0,...,2.0,2.0,1105.0,237.0,1980.0,NaN,-37.73703,145.09392,Eastern Metropolitan,2698.0
23652,Wantirna,16 chesterfield Ct,4.0,h,951000.0,S,Ray,26-08-2017,14.7,3152.0,...,2.0,2.0,704.0,200.0,1981.0,NaN,-37.85639,145.23536,Eastern Metropolitan,5424.0
23653,Wantirna,9 eton Sq,4.0,h,NaN,PI,Ray,26-08-2017,14.7,3152.0,...,2.0,3.0,785.0,NaN,NaN,NaN,-37.85297,145.23815,Eastern Metropolitan,5424.0
23654,Wantirna South,12 Armagh Cr,4.0,h,1323000.0,S,Barry,26-08-2017,14.7,3152.0,...,2.0,2.0,551.0,NaN,NaN,NaN,-37.87608,145.22390,Eastern Metropolitan,7082.0
23655,Wantirna South,34 Fewster Dr,3.0,h,970000.0,S,Barry,26-08-2017,14.7,3152.0,...,2.0,2.0,674.0,NaN,NaN,NaN,-37.88360,145.22805,Eastern Metropolitan,7082.0
23656,Wantirna South,15 Mara Cl,4.0,h,1330000.0,S,Barry,26-08-2017,14.7,3152.0,...,2.0,2.0,717.0,191.0,1980.0,NaN,-37.86887,145.22116,Eastern Metropolitan,7082.0
23657,Watsonia,2/14 Daours Ct,2.0,u,590000.0,S,Lindellas,26-08-2017,14.5,3087.0,...,1.0,1.0,NaN,83.0,2010.0,NaN,-37.71500,145.07649,Northern Metropolitan,2329.0
23658,Watsonia,76 Kenmare St,2.0,h,650000.0,PI,Morrison,26-08-2017,14.5,3087.0,...,1.0,1.0,210.0,79.0,2006.0,NaN,-37.70657,145.07878,Northern Metropolitan,2329.0
23659,Watsonia North,22 Meakin St,3.0,h,NaN,PI,Nelson,26-08-2017,14.5,3087.0,...,2.0,3.0,NaN,NaN,NaN,NaN,-37.70186,145.08635,Northern Metropolitan,1442.0
23660,Werribee,6 Feijoa Ct,5.0,h,NaN,W,YPA,26-08-2017,14.7,3030.0,...,3.0,2.0,535.0,NaN,NaN,NaN,-37.89362,144.66767,Western Metropolitan,16166.0
23661,Werribee,11 Gundaroo Sq,4.0,h,NaN,PI,Stockdale,26-08-2017,14.7,3030.0,...,2.0,6.0,NaN,NaN,NaN,NaN,-37.91230,144.66980,Western Metropolitan,16166.0
23662,Werribee,91 Latham St,4.0,h,540000.0,PI,Triwest,26-08-2017,14.7,3030.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,16166.0
23663,Werribee,5 Nuragi Ct,4.0,h,635000.0,S,hockingstuart,26-08-2017,14.7,3030.0,...,2.0,1.0,662.0,172.0,1980.0,NaN,-37.89327,144.64789,Western Metropolitan,16166.0
23664,Werribee,3 Sky Ct,3.0,h,NaN,PI,Barry,26-08-2017,14.7,3030.0,...,2.0,2.0,NaN,NaN,NaN,NaN,-37.89096,144.64200,Western Metropolitan,16166.0
23665,West Footscray,1/21 Waratah St,2.0,t,655000.0,S,Jas,26-08-2017,6.4,3012.0,...,2.0,1.0,NaN,135.0,2012.0,NaN,-37.80968,144.86819,Western Metropolitan,5058.0
23666,Westmeadows,9 Black St,3.0,h,582000.0,S,Red,26-08-2017,16.5,3049.0,...,2.0,2.0,256.0,NaN,NaN,NaN,-37.67917,144.89390,Northern Metropolitan,2474.0
23667,Westmeadows,81 Hillcrest Dr,4.0,h,720000.0,VB,Barry,26-08-2017,16.5,3049.0,...,2.0,0.0,NaN,NaN,NaN,NaN,-37.68006,144.87550,Northern Metropolitan,2474.0
23668,Wheelers Hill,12 Strada Cr,4.0,h,1245000.0,S,Barry,26-08-2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
23669,Williamstown,77 Merrett Dr,3.0,h,1031000.0,SP,Williams,26-08-2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
23670,Williamstown,83 Power St,3.0,h,1170000.0,S,Raine,26-08-2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
23671,Williamstown,8/2 Thompson St,2.0,t,622500.0,SP,Greg,26-08-2017,6.8,3016.0,...,2.0,1.0,NaN,89.0,2010.0,NaN,-37.86393,144.90484,Western Metropolitan,6380.0
23672,Williamstown,96 Verdon St,4.0,h,2500000.0,PI,Sweeney,26-08-2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
23673,Wyndham Vale,25 Clitheroe Dr,3.0,u,NaN,PN,Harcourts,26-08-2017,27.2,3024.0,...,1.0,0.0,552.0,119.0,1990.0,NaN,-37.90032,144.61839,Western Metropolitan,5262.0
23674,Wyndham Vale,19 Dalrymple Bvd,4.0,h,NaN,S,hockingstuart,26-08-2017,27.2,3024.0,...,NaN,NaN,NaN,NaN,NaN,NaN,-37.87882,144.60184,Western Metropolitan,5262.0
23675,Yallambie,17 Amaroo Wy,4.0,h,1100000.0,S,Buckingham,26-08-2017,12.7,3085.0,...,3.0,2.0,NaN,NaN,NaN,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0
23676,Yarraville,6 Agnes St,4.0,h,1285000.0,SP,Village,26-08-2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0
23677,Yarraville,33 Freeman St,4.0,h,1050000.0,VB,Village,26-08-2017,6.3,3013.0,...,2.0,2.0,NaN,139.0,1950.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0

1- Determine the no. of rows and no. of columns in the dataset?

In [4]:
df.shape

(23678, 21)

              
              The data have 23678 rows and 21 columns.

2. Display the datatypes of each column.

In [5]:
df.dtypes

Suburb            object
Address           object
Rooms            float64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
CouncilArea       object
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

3. Determine the row indexes of rows having all null values (i.e. empty rows).

In [6]:
df.isnull().sum()

Suburb             131
Address            131
Rooms              131
Type               131
Price             5282
Method             131
SellerG            131
Date               131
Distance           132
Postcode           132
Bedroom2          4612
Bathroom          4615
Car               4757
Landsize          6268
BuildingArea     13660
YearBuilt        12138
CouncilArea       8022
Lattitude         4435
Longtitude        4435
Regionname         132
Propertycount      132
dtype: int64

4. Determine the total number of empty rows and their percentage in whole dataset and remove them.

In [12]:
df.isnull().describe()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
count,23678,23678,23678,23678,23678,23678,23678,23678,23678,23678,...,23678,23678,23678,23678,23678,23678,23678,23678,23678,23678
unique,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
top,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
freq,23547,23547,23547,23547,18396,23547,23547,23547,23546,23546,...,19063,18921,17410,13660,12138,15656,19243,19243,23546,23546

5. Determine the column names having missing values.

In [9]:
df.columns[df.isnull().any()]

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

6. Determine the missing values and their percentage in each column.

In [13]:

df.isnull().sum() * 100 / len(df)

Suburb            0.553256
Address           0.553256
Rooms             0.553256
Type              0.553256
Price            22.307627
Method            0.553256
SellerG           0.553256
Date              0.553256
Distance          0.557480
Postcode          0.557480
Bedroom2         19.477996
Bathroom         19.490666
Car              20.090379
Landsize         26.471830
BuildingArea     57.690683
YearBuilt        51.262776
CouncilArea      33.879551
Lattitude        18.730467
Longtitude       18.730467
Regionname        0.557480
Propertycount     0.557480
dtype: float64

7. Determine the row indexes having missing values.

In [17]:
df[df.isnull().any(axis=1)]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2.0,h,NaN,SS,Jellis,03-09-2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2.0,h,1480000.0,S,Biggin,03-12-2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3.0,u,NaN,VB,Rounds,04-02-2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra,-37.81140,145.01160,Northern Metropolitan,4019.0
5,Abbotsford,40 Federation La,3.0,h,850000.0,PI,Biggin,04-03-2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
7,Abbotsford,16 Maugie St,4.0,h,NaN,SN,Nelson,06-08-2016,2.5,3067.0,...,2.0,2.0,400.0,220.0,2006.0,Yarra,-37.79650,144.99650,Northern Metropolitan,4019.0
8,Abbotsford,53 Turner St,2.0,h,NaN,S,Biggin,06-08-2016,2.5,3067.0,...,1.0,2.0,201.0,NaN,1900.0,Yarra,-37.79950,144.99740,Northern Metropolitan,4019.0
9,Abbotsford,99 Turner St,2.0,h,NaN,S,Collins,06-08-2016,2.5,3067.0,...,2.0,1.0,202.0,NaN,1900.0,Yarra,-37.79960,144.99890,Northern Metropolitan,4019.0
10,Abbotsford,129 Charles St,2.0,h,941000.0,S,Jellis,07-05-2016,2.5,3067.0,...,1.0,0.0,181.0,NaN,NaN,Yarra,-37.80410,144.99530,Northern Metropolitan,4019.0
12,Abbotsford,121/56 Nicholson St,2.0,u,NaN,PI,Biggin,07-11-2016,2.5,3067.0,...,2.0,1.0,4292.0,82.0,2009.0,Yarra,-37.80780,144.99650,Northern Metropolitan,4019.0
13,Abbotsford,17 Raphael St,4.0,h,NaN,W,Biggin,07-11-2016,2.5,3067.0,...,2.0,0.0,230.0,147.0,1860.0,Yarra,-37.80660,144.99360,Northern Metropolitan,4019.0
15,Abbotsford,217 Langridge St,3.0,h,1000000.0,S,Jellis,08-10-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
16,Abbotsford,18a Mollison St,2.0,t,745000.0,S,Jellis,08-10-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
17,Abbotsford,6/241 Nicholson St,1.0,u,300000.0,S,Biggin,08-10-2016,2.5,3067.0,...,1.0,1.0,0.0,NaN,NaN,Yarra,-37.80080,144.99730,Northern Metropolitan,4019.0
19,Abbotsford,403/609 Victoria St,2.0,u,542000.0,S,Dingle,08-10-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
20,Abbotsford,2 Rich St,2.0,h,NaN,SP,Biggin,10-12-2016,2.5,3067.0,...,1.0,1.0,176.0,80.0,1925.0,Yarra,-37.79980,144.99720,Northern Metropolitan,4019.0
21,Abbotsford,25/84 Trenerry Cr,2.0,u,760000.0,SP,Biggin,10-12-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
22,Abbotsford,106/119 Turner St,1.0,u,481000.0,SP,Purplebricks,10-12-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
23,Abbotsford,411/8 Grosvenor St,2.0,u,700000.0,VB,Jellis,12-11-2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra,-37.81100,145.00670,Northern Metropolitan,4019.0
26,Abbotsford,22 Park St,4.0,h,1985000.0,S,Biggin,12-11-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,-37.80840,144.99420,Northern Metropolitan,4019.0
27,Abbotsford,13/84 Trenerry Cr,1.0,u,500000.0,S,Biggin,12-11-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
28,Abbotsford,45 William St,2.0,h,1172500.0,S,Biggin,13-08-2016,2.5,3067.0,...,1.0,1.0,195.0,NaN,NaN,Yarra,-37.80840,144.99730,Northern Metropolitan,4019.0
29,Abbotsford,7/20 Abbotsford St,1.0,u,441000.0,SP,Greg,14-05-2016,2.5,3067.0,...,1.0,1.0,0.0,NaN,NaN,Yarra,-37.80160,144.99880,Northern Metropolitan,4019.0
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Abbotsford,16/11 Nicholson St,3.0,u,NaN,PI,Philip,16-04-2016,2.5,3067.0,...,2.0,2.0,0.0,129.0,2010.0,Yarra,-37.80930,144.99590,Northern Metropolitan,4019.0
34,Abbotsford,250 Langridge St,2.0,t,847000.0,S,Jellis,16-07-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
35,Abbotsford,16b Mollison St,2.0,h,NaN,PI,Biggin,16-07-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
37,Abbotsford,196 Nicholson St,3.0,h,955000.0,S,Collins,17-09-2016,2.5,3067.0,...,1.0,0.0,183.0,NaN,NaN,Yarra,-37.80220,144.99750,Northern Metropolitan,4019.0
40,Abbotsford,1/1 Mayfield St,3.0,h,NaN,SP,Nelson,18-03-2017,2.5,3067.0,...,2.0,1.0,119.0,167.0,2005.0,Yarra,-37.80820,144.99990,Northern Metropolitan,4019.0
41,Abbotsford,13/11 Nicholson St,3.0,t,900000.0,S,Beller,18-03-2017,2.5,3067.0,...,2.0,2.0,0.0,NaN,2010.0,Yarra,-37.80930,144.99590,Northern Metropolitan,4019.0
42,Abbotsford,138/56 Nicholson St,3.0,u,1090000.0,S,Jellis,18-03-2017,2.5,3067.0,...,2.0,2.0,4290.0,27.0,NaN,Yarra,-37.80780,144.99650,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23648,Vermont South,2 Settlers Ct,4.0,h,1295000.0,SP,Purplebricks,26-08-2017,17.2,3133.0,...,2.0,2.0,NaN,190.0,1980.0,NaN,-37.85928,145.18715,Eastern Metropolitan,4280.0
23649,Vermont South,9 Winswood Cl,4.0,h,1250000.0,PI,Philip,26-08-2017,17.2,3133.0,...,2.0,2.0,986.0,NaN,NaN,NaN,-37.84679,145.20051,Eastern Metropolitan,4280.0
23650,Viewbank,149 Graham Rd,5.0,h,1316000.0,SP,Nelson,26-08-2017,8.9,3084.0,...,3.0,3.0,696.0,NaN,NaN,NaN,-37.73501,145.08341,Eastern Metropolitan,2698.0
23651,Viewbank,7 Northwood Dr,4.0,h,NaN,SP,Nelson,26-08-2017,8.9,3084.0,...,2.0,2.0,1105.0,237.0,1980.0,NaN,-37.73703,145.09392,Eastern Metropolitan,2698.0
23652,Wantirna,16 chesterfield Ct,4.0,h,951000.0,S,Ray,26-08-2017,14.7,3152.0,...,2.0,2.0,704.0,200.0,1981.0,NaN,-37.85639,145.23536,Eastern Metropolitan,5424.0
23653,Wantirna,9 eton Sq,4.0,h,NaN,PI,Ray,26-08-2017,14.7,3152.0,...,2.0,3.0,785.0,NaN,NaN,NaN,-37.85297,145.23815,Eastern Metropolitan,5424.0
23654,Wantirna South,12 Armagh Cr,4.0,h,1323000.0,S,Barry,26-08-2017,14.7,3152.0,...,2.0,2.0,551.0,NaN,NaN,NaN,-37.87608,145.22390,Eastern Metropolitan,7082.0
23655,Wantirna South,34 Fewster Dr,3.0,h,970000.0,S,Barry,26-08-2017,14.7,3152.0,...,2.0,2.0,674.0,NaN,NaN,NaN,-37.88360,145.22805,Eastern Metropolitan,7082.0
23656,Wantirna South,15 Mara Cl,4.0,h,1330000.0,S,Barry,26-08-2017,14.7,3152.0,...,2.0,2.0,717.0,191.0,1980.0,NaN,-37.86887,145.22116,Eastern Metropolitan,7082.0
23657,Watsonia,2/14 Daours Ct,2.0,u,590000.0,S,Lindellas,26-08-2017,14.5,3087.0,...,1.0,1.0,NaN,83.0,2010.0,NaN,-37.71500,145.07649,Northern Metropolitan,2329.0
23658,Watsonia,76 Kenmare St,2.0,h,650000.0,PI,Morrison,26-08-2017,14.5,3087.0,...,1.0,1.0,210.0,79.0,2006.0,NaN,-37.70657,145.07878,Northern Metropolitan,2329.0
23659,Watsonia North,22 Meakin St,3.0,h,NaN,PI,Nelson,26-08-2017,14.5,3087.0,...,2.0,3.0,NaN,NaN,NaN,NaN,-37.70186,145.08635,Northern Metropolitan,1442.0
23660,Werribee,6 Feijoa Ct,5.0,h,NaN,W,YPA,26-08-2017,14.7,3030.0,...,3.0,2.0,535.0,NaN,NaN,NaN,-37.89362,144.66767,Western Metropolitan,16166.0
23661,Werribee,11 Gundaroo Sq,4.0,h,NaN,PI,Stockdale,26-08-2017,14.7,3030.0,...,2.0,6.0,NaN,NaN,NaN,NaN,-37.91230,144.66980,Western Metropolitan,16166.0
23662,Werribee,91 Latham St,4.0,h,540000.0,PI,Triwest,26-08-2017,14.7,3030.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,16166.0
23663,Werribee,5 Nuragi Ct,4.0,h,635000.0,S,hockingstuart,26-08-2017,14.7,3030.0,...,2.0,1.0,662.0,172.0,1980.0,NaN,-37.89327,144.64789,Western Metropolitan,16166.0
23664,Werribee,3 Sky Ct,3.0,h,NaN,PI,Barry,26-08-2017,14.7,3030.0,...,2.0,2.0,NaN,NaN,NaN,NaN,-37.89096,144.64200,Western Metropolitan,16166.0
23665,West Footscray,1/21 Waratah St,2.0,t,655000.0,S,Jas,26-08-2017,6.4,3012.0,...,2.0,1.0,NaN,135.0,2012.0,NaN,-37.80968,144.86819,Western Metropolitan,5058.0
23666,Westmeadows,9 Black St,3.0,h,582000.0,S,Red,26-08-2017,16.5,3049.0,...,2.0,2.0,256.0,NaN,NaN,NaN,-37.67917,144.89390,Northern Metropolitan,2474.0
23667,Westmeadows,81 Hillcrest Dr,4.0,h,720000.0,VB,Barry,26-08-2017,16.5,3049.0,...,2.0,0.0,NaN,NaN,NaN,NaN,-37.68006,144.87550,Northern Metropolitan,2474.0
23668,Wheelers Hill,12 Strada Cr,4.0,h,1245000.0,S,Barry,26-08-2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
23669,Williamstown,77 Merrett Dr,3.0,h,1031000.0,SP,Williams,26-08-2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
23670,Williamstown,83 Power St,3.0,h,1170000.0,S,Raine,26-08-2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
23671,Williamstown,8/2 Thompson St,2.0,t,622500.0,SP,Greg,26-08-2017,6.8,3016.0,...,2.0,1.0,NaN,89.0,2010.0,NaN,-37.86393,144.90484,Western Metropolitan,6380.0
23672,Williamstown,96 Verdon St,4.0,h,2500000.0,PI,Sweeney,26-08-2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
23673,Wyndham Vale,25 Clitheroe Dr,3.0,u,NaN,PN,Harcourts,26-08-2017,27.2,3024.0,...,1.0,0.0,552.0,119.0,1990.0,NaN,-37.90032,144.61839,Western Metropolitan,5262.0
23674,Wyndham Vale,19 Dalrymple Bvd,4.0,h,NaN,S,hockingstuart,26-08-2017,27.2,3024.0,...,NaN,NaN,NaN,NaN,NaN,NaN,-37.87882,144.60184,Western Metropolitan,5262.0
23675,Yallambie,17 Amaroo Wy,4.0,h,1100000.0,S,Buckingham,26-08-2017,12.7,3085.0,...,3.0,2.0,NaN,NaN,NaN,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0
23676,Yarraville,6 Agnes St,4.0,h,1285000.0,SP,Village,26-08-2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0
23677,Yarraville,33 Freeman St,4.0,h,1050000.0,VB,Village,26-08-2017,6.3,3013.0,...,2.0,2.0,NaN,139.0,1950.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0

8. Determine the missing values and their percentage in each row.

In [18]:
df.apply(lambda x: x.count(), axis=1)

0        18
1        19
2        21
3        18
4        21
5        19
6        21
7        20
8        19
9        19
10       19
11       21
12       20
13       20
14       21
15       12
16       12
17       19
18       21
19       12
20       20
21       12
22       12
23       19
24       21
25       21
26       14
27       12
28       19
29       19
         ..
23648    19
23649    18
23650    18
23651    19
23652    20
23653    17
23654    18
23655    18
23656    20
23657    19
23658    20
23659    16
23660    17
23661    16
23662    12
23663    20
23664    16
23665    19
23666    18
23667    17
23668    19
23669    20
23670    19
23671    19
23672    20
23673    19
23674    13
23675    17
23676    20
23677    19
Length: 23678, dtype: int64

9. Determine the column names having more than 30% missing values and remove them from the dataset.

In [45]:
limitPer = len(df) * .30
df = df.dropna(thresh=limitPer,axis=1)

10. Determine the number and percentage of rows having more than 5 missing values. If the percentage of such 
rows is less than 20% then remove all these rows.

In [48]:
df.drop(df[df.isnull().sum(axis=1)>5].index,axis=0,inplace=True)

print(round(100*(1-df.count()/len(df)),2))

Suburb            0.00
Address           0.00
Rooms             0.00
Type              0.00
Price            21.67
Method            0.00
SellerG           0.00
Date              0.00
Distance          0.00
Postcode          0.00
Bedroom2          0.00
Bathroom          0.01
Car               0.70
Landsize          8.64
BuildingArea     47.43
YearBuilt        39.44
CouncilArea      17.84
Lattitude         0.14
Longtitude        0.14
Regionname        0.00
Propertycount     0.00
dtype: float64

11. Display the description of data and percentage of missing values still left column wise.

In [51]:
perc =[.20, .40, .60, .80]
include =['object', 'float', 'int']
df.describe(percentiles = perc, include = include)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
count,19055,19055,19055.000000,19055,1.492600e+04,19055,19055,19055,19055.000000,19055.000000,...,19054.000000,18921.000000,17408.000000,10018.000000,11540.000000,15656,19029.000000,19029.000000,19055,19055.000000
unique,322,18696,NaN,3,NaN,9,309,58,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,34,NaN,NaN,8,NaN
top,Reservoir,5 Charles St,NaN,h,NaN,S,Nelson,23-09-2017,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Boroondara,NaN,NaN,Southern Metropolitan,NaN
freq,450,5,NaN,13326,NaN,11221,2002,662,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1677,NaN,NaN,7032,NaN
mean,NaN,NaN,2.975020,NaN,1.067117e+06,NaN,NaN,NaN,10.222556,3109.772763,...,1.570956,1.626235,551.822151,154.527895,1964.636742,NaN,-37.812187,145.000471,NaN,7474.095565
std,NaN,NaN,0.972329,NaN,6.382375e+05,NaN,NaN,NaN,6.055921,93.808492,...,0.712765,0.974048,3544.489659,462.535765,37.595504,NaN,0.080002,0.106099,NaN,4312.653403
min,NaN,NaN,1.000000,NaN,8.500000e+04,NaN,NaN,NaN,0.000000,3000.000000,...,0.000000,0.000000,0.000000,0.000000,1196.000000,NaN,-38.184180,144.431620,NaN,129.000000
20%,NaN,NaN,2.000000,NaN,5.950000e+05,NaN,NaN,NaN,5.300000,3041.000000,...,1.000000,1.000000,140.000000,86.000000,1930.000000,NaN,-37.872224,144.918880,NaN,3619.000000
40%,NaN,NaN,3.000000,NaN,7.920000e+05,NaN,NaN,NaN,8.000000,3073.000000,...,1.000000,1.000000,318.000000,115.000000,1960.000000,NaN,-37.829836,144.987700,NaN,5549.000000
50%,NaN,NaN,3.000000,NaN,9.000000e+05,NaN,NaN,NaN,9.200000,3101.000000,...,1.000000,2.000000,448.000000,129.000000,1970.000000,NaN,-37.809260,145.004690,NaN,6567.000000
60%,NaN,NaN,3.000000,NaN,1.024000e+06,NaN,NaN,NaN,11.000000,3124.000000,...,2.000000,2.000000,560.000000,145.000000,1975.000000,NaN,-37.790200,145.026098,NaN,7717.000000
80%,NaN,NaN,4.000000,NaN,1.430000e+06,NaN,NaN,NaN,13.900000,3165.000000,...,2.000000,2.000000,696.000000,196.000000,2002.200000,NaN,-37.747700,145.078058,NaN,10969.000000
max,NaN,NaN,10.000000,NaN,9.000000e+06,NaN,NaN,NaN,48.100000,3977.000000,...,12.000000,26.000000,433014.000000,44515.000000,2106.000000,NaN,-37.407580,145.526350,NaN,21650.000000

12. Considering the 'Price' column as target variable which is to be predicted, how will you treat the missing values? 
Give a brief explanation and treat the missing values in 'Price' column.

In [52]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2.0,h,NaN,SS,Jellis,03-09-2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2.0,h,1480000.0,S,Biggin,03-12-2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2.0,h,1035000.0,S,Biggin,04-02-2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3.0,u,NaN,VB,Rounds,04-02-2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3.0,h,1465000.0,SP,Biggin,04-03-2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0

In [54]:
df['Price'].isnull().sum()

4129

If i have to train the data as a target with price column i can replace price columns with its median or mean for entire dataset for best prediction result.

In [55]:
df['Price'].fillna((df['Price'].mean()), inplace=True)

In [56]:
df['Price'].isnull().sum()

0

   Now there is no null values present in df['price'] ,  all the values are replace by its mean value.

13. Now check the percentage of missing values in each column again, if missing values exist, treat it with the most 
suitable method.

In [57]:

df.isnull().sum() * 100 / len(df)

Suburb            0.000000
Address           0.000000
Rooms             0.000000
Type              0.000000
Price             0.000000
Method            0.000000
SellerG           0.000000
Date              0.000000
Distance          0.000000
Postcode          0.000000
Bedroom2          0.000000
Bathroom          0.005248
Car               0.703227
Landsize          8.643401
BuildingArea     47.425872
YearBuilt        39.438468
CouncilArea      17.837838
Lattitude         0.136447
Longtitude        0.136447
Regionname        0.000000
Propertycount     0.000000
dtype: float64

In [59]:
df=df.fillna(df.mean())

In [60]:
df.isnull().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
YearBuilt           0
CouncilArea      3399
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

In [63]:

df.drop(['CouncilArea'], axis = 1,inplace = True)

In [64]:
df.isnull().sum()

Suburb           0
Address          0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Date             0
Distance         0
Postcode         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
YearBuilt        0
Lattitude        0
Longtitude       0
Regionname       0
Propertycount    0
dtype: int64

All missing values are treated.

14. Now since you have completed your data cleaning, determine the number and percentage of columns removed.

In [70]:
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'Lattitude', 'Longtitude',
       'Regionname', 'Propertycount'],
      dtype='object')

In [74]:
df['percent'] = (df['Price'] / df['Price'].sum()) * 100

In [76]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Regionname,Propertycount,percent
0,Abbotsford,68 Studley St,2.0,h,1.067117e+06,SS,Jellis,03-09-2016,2.5,3067.0,...,1.0,1.0,126.0,154.527895,1964.636742,-37.8014,144.9958,Northern Metropolitan,4019.0,0.005248
1,Abbotsford,85 Turner St,2.0,h,1.480000e+06,S,Biggin,03-12-2016,2.5,3067.0,...,1.0,1.0,202.0,154.527895,1964.636742,-37.7996,144.9984,Northern Metropolitan,4019.0,0.007278
2,Abbotsford,25 Bloomburg St,2.0,h,1.035000e+06,S,Biggin,04-02-2016,2.5,3067.0,...,1.0,0.0,156.0,79.000000,1900.000000,-37.8079,144.9934,Northern Metropolitan,4019.0,0.005090
3,Abbotsford,18/659 Victoria St,3.0,u,1.067117e+06,VB,Rounds,04-02-2016,2.5,3067.0,...,2.0,1.0,0.0,154.527895,1964.636742,-37.8114,145.0116,Northern Metropolitan,4019.0,0.005248
4,Abbotsford,5 Charles St,3.0,h,1.465000e+06,SP,Biggin,04-03-2017,2.5,3067.0,...,2.0,0.0,134.0,150.000000,1900.000000,-37.8093,144.9944,Northern Metropolitan,4019.0,0.007205

15. Determine the number and percentage of rows removed in whole process. Also comment briefly that according 
to you the amount of data lost is justified or not.

In [77]:
df.shape

(19055, 21)

Now our dataset have 19055 rows which means 4622 rows are deleted and remaing are replaced , so i think this is best for the model because by so much drop data the model does not learn so much or by access null values model does not work , by which it goes into overfitting and underfitting easily.